### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by anyars-encarta** [MozamelJawad/My_Portfolio#15]
Good work, absolute design and nice presentation of code. However, I observed that a line in your ode needs autocomplete attribute to be completed. Check the reference below:

https://github.com/MozamelJawad/My_Portfolio/blob/4a11589205d2442d8ef4d633d242e10f91e10a88/index.html#L139

**Comment by MozamelJawad** [comment]
Okay, thanks for your review and for making informed me
